site_name: Ansible Playground
site_description: Learn your way into the Ansible Playbooks and roles
copyright: This project is maintained by Vamshi Siddarth Gaddam
repo_name: vamshisiddarth/ansible_playground
repo_url: https://github.com/vamshisiddarth/ansible_playground
site_url: https://vamshisiddarth.github.io/ansible_playground
site_author: Vamshi Siddarth Gaddam

# Theme Configuration for the Github Pages
theme:
  name: material
  #  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

nav:
  - Home: 'index.md'
  - 'Quick Start Guide': 'Quick-Start.md'
  - 'Destroy Resources': 'demolition.md'

google_analytics:
  - G-YQJ1M18N29
  - auto