---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags
- name: debug
  debug: msg={{ [env,idx,ecname,ecnameidx] }}
  tags:
    - never
    - debug

- name: debug
  debug: msg={{ hostvars[inventory_hostname].tags }}
  tags:
    - never
    - debug


- name: include base debian
  import_tasks: base-debian.yml
  when: is_debian == True
  tags:
    - base-deploy
    - base-pkgs

- name: include limits
  import_tasks: limits.yml
  tags:
    - limits-deploy

- name: include zsh ubuntu
  import_tasks: zsh.yml
  vars:
    user: ubuntu
  when: is_debian == True
  tags:
    - base-deploy
    - zsh-deploy

- name: include zshroot
  import_tasks: zsh.yml
  vars:
    user: root
    home_dir: '/'
  tags:
    - base-deploy
    - zsh-deploy

- name: include keys
  import_tasks: keys.yml
  tags:
    - keys-deploy
    - base-deploy
